"""
Proposed-amendment PDF generator.

Produces a DRAFT amended copy of the Valuation (and, where applicable, the
Building Survey) for HUMAN SIGN-OFF. The original file is never modified —
we always work on a copy in memory and stamp it as a proposal.

Authoritative rules (Alex Hromova, 29 Jun 2026):
  * Valuation: amend ONLY checkboxes + specific values — NOT the template.
      - tick the correct "Type of Property" + "Type of Building" checkbox
      - update the "Number of bedrooms" value (page 2)
  * "Output a PDF with human sign-off prior to any changes."
  * Never silently finalise edits to sensitive reports.

Anything we cannot locate/apply safely is left for a human and clearly noted on
the proposal's cover banner (so the field stays FLAGGED, not silently dropped).
"""
from __future__ import annotations

import io
from typing import Optional

try:
    import fitz  # PyMuPDF
    HAS_FITZ = True
except ImportError:
    HAS_FITZ = False

from app.schemas.models import Amendment, AmendAction
from app.agents.amendments import (
    valuation_checkboxes_for, bedrooms_to_int,
    VAL_TYPE_OF_PROPERTY, VAL_TYPE_OF_BUILDING,
)

# RGB for the proposal mark-ups
_RED = (0.85, 0.1, 0.1)
_BLUE = (0.1, 0.25, 0.75)


def _add_cover_banner(doc, title: str, lines: list[str]):
    """Prepend a cover page making it unmistakable this is a DRAFT for sign-off."""
    page = doc.new_page(pno=0, width=595, height=842)  # A4
    page.draw_rect(fitz.Rect(0, 0, 595, 90), color=_RED, fill=_RED)
    page.insert_textbox(
        fitz.Rect(30, 22, 565, 80),
        "PROPOSED AMENDMENT — NOT FINALISED\nRequires human sign-off before use",
        fontsize=16, color=(1, 1, 1), fontname="hebo", align=1,
    )
    page.insert_textbox(
        fitz.Rect(30, 110, 565, 160), title,
        fontsize=13, color=(0, 0, 0), fontname="hebo",
    )
    y = 175
    for ln in lines:
        page.insert_textbox(
            fitz.Rect(30, y, 565, y + 60), ln,
            fontsize=10.5, color=(0.1, 0.1, 0.1), fontname="helv",
        )
        y += 26
    page.insert_textbox(
        fitz.Rect(30, 760, 565, 820),
        "Generated by the Irish Homes MTR Batch Tool. The Submission Sheet (SS) is the "
        "master document. The proposed changes below have NOT been applied to the "
        "original report — they are drafted here for a reviewer to check and sign off.",
        fontsize=8.5, color=(0.35, 0.35, 0.35), fontname="helv",
    )


def _tick_checkbox_near(page, label: str) -> bool:
    """Find `label` on the page and draw a tick in the box to its right.

    Returns True if the label (and a plausible box position) was found.
    """
    rects = page.search_for(label, quads=False)
    if not rects:
        return False
    lbl = rects[0]
    # The checkbox sits just to the right of the label on these forms (image3).
    box = fitz.Rect(lbl.x1 + 6, lbl.y0 - 1, lbl.x1 + 26, lbl.y1 + 1)
    # draw a bold tick
    page.draw_line(fitz.Point(box.x0 + 3, box.y0 + (box.height / 2)),
                   fitz.Point(box.x0 + 8, box.y1 - 2), color=_RED, width=1.8)
    page.draw_line(fitz.Point(box.x0 + 8, box.y1 - 2),
                   fitz.Point(box.x1 - 2, box.y0 + 1), color=_RED, width=1.8)
    page.draw_rect(box, color=_RED, width=0.8)
    return True


def _annotate_value(page, anchor: str, new_value: str) -> bool:
    """Write `new_value` just to the right of the `anchor` label, in red."""
    rects = page.search_for(anchor, quads=False)
    if not rects:
        return False
    a = rects[0]
    page.insert_text(fitz.Point(a.x1 + 10, a.y1 - 1),
                     f"→ {new_value}", fontsize=11, color=_RED, fontname="hebo")
    return True


def propose_valuation_pdf(
    original_bytes: bytes,
    amendments: list[Amendment],
    ss_property_type: Optional[str],
    ss_bedrooms,
) -> tuple[Optional[bytes], list[str], list[str]]:
    """Return (pdf_bytes, applied_notes, unapplied_notes).

    Builds a draft amended Valuation. Only checkboxes + the bedroom value are
    touched. Anything not locatable is reported in unapplied_notes so it stays
    a FLAG for the human, never silently dropped.
    """
    if not HAS_FITZ:
        return None, [], ["PyMuPDF not available — cannot render proposed PDF; FLAG only."]

    applied: list[str] = []
    unapplied: list[str] = []

    try:
        doc = fitz.open(stream=original_bytes, filetype="pdf")
    except Exception as e:
        return None, [], [f"Could not open Valuation PDF ({e}); FLAG only."]

    # Which fields are proposed for this doc?
    prop_type_pending = any(
        a.document == "valuation" and a.field.startswith("Property Type")
        and a.action == AmendAction.PROPOSED for a in amendments)
    beds_pending = any(
        a.document == "valuation" and a.field == "Number of Bedrooms"
        and a.action == AmendAction.PROPOSED for a in amendments)

    # ── Property type checkboxes (page 1) ──
    if prop_type_pending:
        form, building = valuation_checkboxes_for(ss_property_type)
        page1 = doc[0]
        for label, wanted in (("Type of Property", form), ("Type of Building", building)):
            if not wanted:
                continue
            if _tick_checkbox_near(page1, wanted):
                applied.append(f"Ticked {label}: '{wanted}' (page 1)")
            else:
                unapplied.append(
                    f"Could not locate the '{wanted}' checkbox for {label} on page 1 — "
                    f"FLAG: tick it manually to match SS.")

    # ── Bedrooms (page 2) ──
    if beds_pending:
        target = bedrooms_to_int(ss_bedrooms)
        done = False
        if target is not None:
            page = doc[1] if doc.page_count > 1 else doc[0]
            for anchor in ("Number of bedrooms", "Bedrooms", "Number of Beds"):
                if _annotate_value(page, anchor, str(target)):
                    applied.append(f"Marked Bedrooms → {target} (page {page.number + 1})")
                    done = True
                    break
        if not done:
            unapplied.append(
                f"Could not locate the bedrooms field — FLAG: set bedrooms = "
                f"{bedrooms_to_int(ss_bedrooms)} manually to match SS.")

    if not applied and not unapplied:
        doc.close()
        return None, [], []

    # Cover banner summarising the proposal
    banner_lines = [f"• {n}" for n in applied] + [f"• (NOT applied) {n}" for n in unapplied]
    _add_cover_banner(
        doc, "Proposed amended VALUATION REPORT (checkboxes & bedrooms only)",
        banner_lines or ["No changes could be applied automatically — see control sheet."])

    out = io.BytesIO()
    doc.save(out)
    doc.close()
    return out.getvalue(), applied, unapplied
